name: flutter_application_4_scafold
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
environment:
  sdk: '>=2.12.0 <4.0.0'
# Votre déclaration "flutter: assets:" va ici
flutter:
  assets:
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
    - assets/image6.jpg
    - assets/image7.jpg
    - assets/image8.jpg
    - assets/image9.jpg
    - assets/image10.jpg
fonts:
  - family: MaterialIcons
    fonts:
      - asset: packages/material_design_icons/icons/MaterialIcons-Regular.ttf
